language: java
jdk:
- oraclejdk8
sudo: false
notifications:
  slack:
    secure: D+zPCR1CfaOoEt1WkKiZtqhjo7dBDNkd4AHQPuO7McdLGukLTnXrvQORoWQdXxuBOpddf52AOI1D+0sz652rP5cfPJmp/qlEjRsZwhXB40KyMuBJD7eWvMiaCslsRfPu+1PUmFcH3niJyWa4YJ7XOsjhLG2UHsXoUBgdU1LjECfIahqh0X6RDZlPXpSM6XumufdVxurbq4c4fHhxU0NI5FgaNwXygizSLUB/11lzJ+Uk1UDzu650HFqCUpMLGGX9NdVkOOOn1VHFImxqBRwowUWYV4sq3MGCEOxfS62D4m4WlUBh1KdDbzZi4km1A/juNYut1A6UCfumRN0JFTJiTJjnYkTerj//Nfck1BuyK5aHQWmseJJOuetLDyWnrECUgvMgDL7IFnOpH3HIr/h0JEAlcaHWb+CbH/SCvCKjiKp+XZW4J2s9BOLHu+nQLYRirmdXJzRe8ukaBWE51+Av2q1Ny6uZtt2sX4vx6/BZtj+hz7B89MIzIknE3sscK68D4dD8YVUqPYFIWI20szzdtYWa7YA63yJLxXSn/6cb3STe1yyUVAnLmZudOLEFMmE1/v5SlDQQQi1o+KOn6HEf4mmisDnH2NT97bay3JnhBZHZEd9nY839sSCer0Z7m3AADJbLybe3TvjhLIBlcAiHSvo71nCKdWD3i5zptztJY2g=
after_success:
- mvn clean test org.jacoco:jacoco-maven-plugin:report org.eluder.coveralls:coveralls-maven-plugin:report
